name: Frontend CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hotel-project-client-main

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: 패키지 설치
        run: npm install

      - name: .env 파일 생성
        run: |
          echo "${{ secrets.ENV_PRODUCTION }}" > .env

      - name: Vite 프로젝트 빌드 (dist 폴더 생성)
        run: npm run build

      - name: AWS 자격 증명 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: S3에 빌드 파일 업로드
        run: aws s3 sync dist/ s3://${{ vars.AWS_S3_BUCKET_NAME }} --delete

      - name: CloudFront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"